### PR TITLE
c100411004

### PR DESCRIPTION
**Pull request by LogicalNonsense2051**
Added "Harpie’s Feather Roosting".

### CODE REVIEW

**Comment by EerieCode** [comment]
A few things to say about it:
- The effect e1 is missing the type EFFECT_TYPE_ACTIVATE;
- The two cards mentioned in the card text have constants avaiable, CARD_HARPIE_LADY and CARD_HARPIE_LADY_SISTER. It's not technically an error, but might as well use them since we have them;
- I see you used the ct variable in the target to say how many cards should be drawn: you should use it in SetOperationInfo and IsPlayerCanDraw as well, to ensure everything is accurate.

**Comment by EerieCode** [comment]
There's a missing parenthesis at line 10. Also, I just noticed you left a c100411001 at line 27. Aside from that, it seems fine.

**Comment by LogicalNonsense2051** [comment]
Alright, thanks for the review. Updated it to mostly what you've pointed out and will keep the constants in mind for similar future applications. Editing on mobile is a lot more annoying than I expected (created it before I left the house for classes)...

**Comment by EerieCode** [comment]
Yeah, I usually don't even bother when I'm on cell, it's just too impractical. I made a little fix I missed, BTW, ct wasn't declared in the target so it would have given an error later.

**Pull request merged**
